services:
  factorio:
    image: factoriotools/factorio:stable
    ports:
      - "34197:34197/udp"
      - "27015:27015/tcp"
    volumes:
      - /opt/factorio:/factorio
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.scope=${COMPOSE_PROJECT_NAME}"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 30
    environment:
      WATCHTOWER_NO_STARTUP_MESSAGE: "true"
      WATCHTOWER_REMOVE_VOLUMES: "true"
      WATCHTOWER_ROLLING_RESTART: "true"
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_SCOPE: "${COMPOSE_PROJECT_NAME}"
      TZ: "Asia/Taipei"
      WATCHTOWER_NOTIFICATION_REPORT: "true"
      WATCHTOWER_NOTIFICATION_URL: >
        discord://${DISCORD_WEBHOOK_TOKEN}@${DISCORD_WEBHOOK_ID}
      WATCHTOWER_NOTIFICATION_TEMPLATE: |
        {{- if .Report -}}
          {{- with .Report -}}
            {{- if ( or .Updated .Failed ) -}}
              **Watchtower Report Summary**
              - **Scanned:** {{len .Scanned}}
              - **Updated:** {{len .Updated}}
              - **Failed:** {{len .Failed}}

              {{- if .Updated}}
              **Updated Containers:**
              {{- range .Updated}}
              - **{{.Name}}** ({{.ImageName}})
                - Current ID: `{{.CurrentImageID.ShortID}}`
                - Updated to: `{{.LatestImageID.ShortID}}`
              {{- end -}}
              {{- end}}

              {{- if .Skipped}}
              **Skipped Containers:**
              {{- range .Skipped}}
              - **{{.Name}}** ({{.ImageName}})
                - Status: `{{.State}}`
                - Error: `{{.Error}}`
              {{- end -}}
              {{- end}}

              {{- if .Failed}}
              **Failed Containers:**
              {{- range .Failed}}
              - **{{.Name}}** ({{.ImageName}})
                - Status: `{{.State}}`
                - Error: `{{.Error}}`
              {{- end -}}
              {{- end}}
            {{- end -}}
          {{- end -}}
        {{- else -}}
          **General Notifications:**
          {{range .Entries -}}
          {{.Message}}{{"\n"}}
          {{- end -}}
        {{- end -}}
