services:
  mapshot-server:
    container_name: mapshot-server
    build:
      context: .
      dockerfile: Dockerfile-mapshot
    image: factorio-mapshot:latest
    volumes:
      - ${FACTORIO_DIR_PATH}/saves:/opt-factorio-saves
      - ${MAPSHOT_DIR_PATH}:/mapshot
    ports:
      - "5003:8080"
    environment:
      MAPSHOT_MODE: "serve"

  mapshot-renderer:
    container_name: mapshot-renderer
    image: factorio-mapshot:latest
    volumes:
      - ${FACTORIO_DIR_PATH}/saves:/opt-factorio-saves
      - ${MAPSHOT_DIR_PATH}:/mapshot
    environment:
      RELEASE_TYPE: ${RELEASE_TYPE}
      FACTORIO_USERNAME: ${FACTORIO_USERNAME}
      FACTORIO_TOKEN: ${FACTORIO_TOKEN}
      FACTORIO_SAVE: /opt-factorio-saves/${FACTORIO_SAVE}
      MAPSHOT_AREA: ${MAPSHOT_AREA:-_all_}
      MAPSHOT_JPEG_QUALITY: ${MAPSHOT_JPEG_QUALITY:-95}
      MAPSHOT_MINIMUM_JPEG_QUALITY: ${MAPSHOT_MINIMUM_JPEG_QUALITY:-95}
      MAPSHOT_MINIMUM_TILES: ${MAPSHOT_MINIMUM_TILES:-64}
      MAPSHOT_MODE: "render"
      MAPSHOT_SURFACES_TO_RENDER: ${MAPSHOT_SURFACES_TO_RENDER:-_all_}
      MAPSHOT_VERBOSE_MAPSHOT_LOG_LEVEL_INT: ${MAPSHOT_VERBOSE_MAPSHOT_LOG_LEVEL_INT:-9}
      MAPSHOT_INTERVAL: ${MAPSHOT_INTERVAL:-600}
    restart: always

  restarter:
    container_name: mapshot-renderer-restarter
    image: docker:cli
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      RESTART_TIMES: ${RESTART_TIMES:-"00 30"}
      STOP_TIMEOUT: ${STOP_TIMEOUT:-10}
    entrypoint: ["/bin/sh","-c"]
    command: 
      - |
        while true; do
          minute=$$(date +'%M');
          for target_minute in $${RESTART_TIMES}; do
            if [ "$$minute" = "$$target_minute" ]; then
              docker stop --time=$${STOP_TIMEOUT} mapshot-renderer;
              docker start mapshot-renderer;
              break;
            fi
          done
          sleep 60;
        done
